"""One-time: pull all subscriptions, LLM-classify against interests,
write config/channels.yaml. Re-run any time; hand-edit the output freely.

Needs env vars: OPENROUTER_API_KEY, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET,
GOOGLE_REFRESH_TOKEN.
"""
import json
import pathlib
import sys

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from src import curate, llm, youtube  # noqa: E402

yt = youtube.get_service()
subs, token = [], None
while True:
    resp = yt.subscriptions().list(
        part="snippet", mine=True, maxResults=50, pageToken=token
    ).execute()
    subs += [{
        "id": s["snippet"]["resourceId"]["channelId"],
        "title": s["snippet"]["title"],
        "description": s["snippet"]["description"][:200],
    } for s in resp.get("items", [])]
    token = resp.get("nextPageToken")
    if not token:
        break
print(f"{len(subs)} subscriptions found")

result = curate.parse_llm_json(llm.complete(
    "curation",
    f"""My interests:
{curate.interests_text()}

My YouTube subscriptions:
{json.dumps(subs, indent=1)}

Return JSON: {{"channels": [{{"id", "title"}}]}} — ONLY the channels likely to
publish videos relevant to my interests. Be selective; lifestyle/entertainment
channels are out even if I subscribe to them.""",
    system="Respond with a single JSON object and nothing else.",
))

out = pathlib.Path("config/channels.yaml")
out.write_text(
    "# Generated by scripts/curate_channels.py — hand-edit freely.\n"
    + yaml.safe_dump({"channels": result["channels"]}, allow_unicode=True),
    encoding="utf-8",
)
print(f"wrote {out} with {len(result['channels'])} channels")
